---
username: kitchen
ssh_key: "/Ansible/roles/apache/.kitchen/docker_id_rsa"
image_id: 8eb74e143aca
container_id: bf73d2f8f9b18d367cd492ec19710ea2a7c79f1ea65279b1a33b5587ea1448c6
hostname: localhost
port: 32772
last_action: converge
last_error: 
